### PR TITLE
Enter v3 beta cycle / The SW3 commit

### PR DESCRIPTION
**Pull request by frostburn**
**Warning!** Merging this PR will cause `main` to enter beta cycle where key features like URL sharing are disabled until a backend is implemented.
The state of `main` prior to merging will become `two` and continue to receive v2 bug fixes until it's deprecated at the end of v3 beta cycle.

This commit swaps out the core engine from scale-workshop-core to sonic-weave.
Too many breaking changes have been introduced to maintain an incremental commit history at this juncture.

### CODE REVIEW

**Comment by arseniiv** [comment]
Well some exporter tests are failing on Windows because of pesky `\r\n` incursion but I plan to look at that. Other than that I don’t know what to look for, so…

**Comment by frostburn** [comment]
> Well some exporter tests are failing on Windows because of pesky `\r\n` incursion but I plan to look at that. Other than that I don’t know what to look for, so…

I just fixed some cross-platform issues in `main`. Let me rebase this PR to see if they persist...

**Comment by frostburn** [comment]
Found and removed some commented out code during self-review.
Personally I'm OK with entering beta cycle.
@inthar-raven Any objections? It would mean that you'd need to redo #622 in order to target SW3.

**Comment by inthar-raven** [comment]
> Found and removed some commented out code during self-review. Personally I'm OK with entering beta cycle. @inthar-raven Any objections? It would mean that you'd need to redo #622 in order to target SW3.

No objections. It's on me that I didn't look into some important things, anyway.

**Comment by inthar-raven** [comment]
> Found and removed some commented out code during self-review. Personally I'm OK with entering beta cycle. @inthar-raven Any objections? It would mean that you'd need to redo #622 in order to target SW3.

No objections. It's on me that I didn't look into some important things pertaining to SW3, anyway.

**Comment by frostburn** [comment]
I guess we're doing this now. :rocket:

**Pull request merged**
