### PR TITLE
Add a link to the new Discord channel over at Xenharmonic Alliance

### PR DESCRIPTION
**Pull request by frostburn**
ref #468

### CODE REVIEW

**Comment by frostburn** [comment]
image
Doesn't look pretty on a smartphone.

@SeanArchibald any quick tips on how to lay this out?

**Comment by SeanArchibald** [comment]
Screenshot_20240106_170734

If you add `justify-content: center` on that element with class 'control' then I think it looks pretty good

**Comment by frostburn** [comment]
Thanks! Added a scoped class with that.

**Comment by SeanArchibald** [comment]
Looks good to me

**Pull request merged**
