### PR TITLE
Add sanity checks for user input

### PR DESCRIPTION
**Pull request by frostburn**
ref #144

### CODE REVIEW

**Review by SeanArchibald — CHANGES_REQUESTED** [review]
Nice stuff, I didn't realise until now but this is a really good improvement to have.

I tried to create 9999ed2. What I ended up with was the clamped 1024ed2 which is fine but the scale name was still set to "9999 equal divisions of 2/1". The HTML input field itself could have max="1024" too.

Trying to create harmonics 1-10001 still takes a couple minutes on this 2015 MacBook Air, then page performance continues to be really bad. I'm wondering if the limit should be more strict. Even 1-1000 was very slow.

For approximate by ratios > odd limit, I tried to type in 300 but the page instantly froze with 30 in the input box. It did come back after a couple mins. To replicate the issue again a page refresh is needed. On my phone, I had a much larger scale active and had to force close the tab.

**Comment by frostburn** [comment]
The ET modal is a difficult beast to tame. A subset of 9999ed2 is fine so we can't have a hard `max="1024`. I'll check if anything can be done about the scale name.

**Comment by frostburn** [comment]
I was only testing on a beefy desktop computer. I'll try tuning the limits to be more mobile friendly.

**Comment by frostburn** [comment]
Fixed the issues. Deploying and testing on a smartphone...

**Comment by frostburn** [comment]
My phone didn't blow up. Good for review again.
I'm not worried about large performance drops. The user is shooting themselves in the foot when running into the limits anyway.

**Pull request merged**
