### PR TITLE
Stop Firefox from bringing up Quick Find when '/' is pressed

### LINKED ISSUE #407: Stop Firefox from opening Quick Find when '/' key is pressed
Firefox has a feature called "Quick Find" which makes the slash key bring up a search bar unless text is being entered. This interferes with the using the keyboard for notes in Scale Workshop.

A fix has been provided.

### PR DESCRIPTION
**Pull request by forrcaho**
Fixes #407

### CODE REVIEW

**Comment by frostburn** [comment]
I find this solution too heavy-handed.  It's not the job of a key-press wrapper to interfere with default browser behavior. Maybe `App.windowKeydown` is a better place for this.

**Comment by forrcaho** [comment]
This fix is based on [a StackOverflow answer](https://stackoverflow.com/a/8563788). Notice that it has to check that the focus is not on an input element before reclaiming the key event from Firefox.

By inserting the line where I did, the focus state is known: any keydown event executing that code is intended to play a note. 

I'm not familiar with `App.windowKeydown`, but I worry that putting this code elsewhere would mean that the focus check would have to be duplicated.

**Comment by frostburn** [comment]
I'm pretty sure this fix can be placed near the focus check without having to worry about code duplication. I can take a crack at it later. The fix itself is welcome. :pray:

**Comment by frostburn** [comment]
Rejected in favor of #409

**Pull request closed without merging**
