### PR TITLE
Implement automatic key colors based on scale size

### PR DESCRIPTION
**Pull request by frostburn**
refs #53

### CODE REVIEW

**Review by SeanArchibald — COMMENTED** [review]
I approve in principal about the changes here, though one example I tested was 17ed2 and the result was:

white white black white white white white white white white black white white white white white white

It seems a really weird key layout for me with 15 white notes and 2 black notes so I'm not sure if this was intended.

**Comment by frostburn** [comment]
Such extreme scales are not intended. I'll check if using fifth-based scales helps.

**Comment by frostburn** [comment]
Changed to fifth/fourth based construction. Mavila edos still get only two black keys (as they should IMHO), but 17 gets more now.

**Comment by SeanArchibald** [comment]
Works well, looks good to merge

**Pull request merged**
