### PR TITLE
Implement mapping from white MIDI keys to white key colors

### PR DESCRIPTION
**Pull request by frostburn**
ref #280

### CODE REVIEW

**Comment by SeanArchibald** [comment]
Seems this one is to do with MIDI I/O? I'm not really in a position to test it. Might need to get feedback from another dev or user for this one.

**Comment by frostburn** [comment]
Yeah it's MIDI I/O. I can update the beta server for ease of testing once #294 is merged out of the way.

**Comment by frostburn** [comment]
**Sevish** — Today at 9:25 PM

> does the behaviour always assume 69 is the base?

**Comment by frostburn** [comment]
I guess this needs some unit tests to specify how everything is supposed to interact...

**Comment by frostburn** [comment]
Fixed issues with base MIDI note != 69 and duplicate notes.

**Review by SeanArchibald — APPROVED** [review]

**Pull request merged**
