### PR TITLE
Update sonic-weave dependency

### PR DESCRIPTION
**Pull request by frostburn**
Adds stepString() which labels the last interval in the scale with the step pattern.
Fix parsing if negative integers.
Make function parameters required by default.
Add array access with arrays of indices and of booleans.

### CODE REVIEW

**Review by inthar-raven — COMMENTED** [review]
This commit would just update `main` to beta 3, right?

**Comment by frostburn** [comment]
> This commit would just update `main` to beta 3, right?

Correct.

**Comment by inthar-raven** [comment]
Does the array access with indices work like `map array indices` (in pseudo-Haskell, viewing the array as a function)? And the Boolean thing is the array applied to the `true` indices, right?

**Comment by frostburn** [comment]
> Does the array access with indices work like `map array indices` (in pseudo-Haskell, viewing the array as a function)? And the Boolean thing is the array applied to the `true` indices, right?

It's been a while since I've programmed in Haskell. I think what you're saying is true. The model I'm trying to emulate is numpy for Python.

**Review by inthar-raven — APPROVED** [review]

**Pull request merged**
