### PR TITLE
Make virtual keyboard text color dynamic based on background

### PR DESCRIPTION
**Pull request by frostburn**
Use white text with dark backgrounds and black text with light background.

ref #661

### CODE REVIEW

**Comment by frostburn** [comment]
@wilckerson Would you mind reviewing this solution to virtual keyboard contrast issues?

**Review by wilckerson — APPROVED** [review]
Awesome. This brightness-based approach to deciding the light/dark complement is interesting.

**Comment by wilckerson** [comment]
Since this PR is related to UI changes, do you have any screenshots of how it is looking?

**Comment by frostburn** [comment]
> Since this PR is related to UI changes, do you have any screenshots of how it is looking?

image

**Comment by frostburn** [comment]
Judging as accepted based on the heart emoji and lack of explicit rejection.

**Comment by wilckerson** [comment]
Yeah, It looks awesome. Sorry, for not being more clear with my message.

**Pull request merged**
