### PR TITLE
Remove an extra zero from Korg maximum cents limit

### PR DESCRIPTION
**Pull request by frostburn**
ref #393

### CODE REVIEW

**Comment by SeanArchibald** [comment]
I'm still not getting the expected tuning when I import the mnlgtns file from this branch into the monologue Sound Librarian. The result is different to both SW 1.x and SW 2.0.0, so I've pasted screenshots of all three below.

Test scale http://localhost:3000/scaleworkshop/?n=CPS%20%282%20of%201%203%205%209%20over%203%2F2%29%20B%3D243Hz&l=aF9_wFr_8wF6r_4F3_14Fr_3F2&f=6r&m=1n&version=2.0.1

SW1 output (correct)
SW1 result

SW2.0.0 output
SW2 0 0 result

fix-korg-limit branch output
fix-korg-limit result

**Comment by znmeb** [comment]
I have a Minilogue XD if you need someone to test it. I have found some inconsistencies in how the Sound Librarian handles .scl files.

**Comment by frostburn** [comment]
@znmeb Inconsistencies between Sound Librarian and other .scl compatible software (their fault) or inconsistencies between .scl and .mnlgtuns (our fault)? Can you provide a link to a scale with issues?

**Comment by znmeb** [comment]
> @znmeb Inconsistencies between Sound Librarian and other .scl compatible software (their fault) or inconsistencies between .scl and .mnlgtuns (our fault)? Can you provide a link to a scale with issues?

Definitely Korg's fault! and definitely the Sound Librarian - I can reproduce it without sending the scale to the Minilogue XD. I didn't use Scale Workshop at all, just Scala.

It's really two problems. I am using the 1-3-5-7-9-11 Eikosany, which has 20 scale degrees.

1. Missing documentation: If you give the Sound Librarian a `.scl` file without a `.kbm` file, it assumes you want to map the keyboard starting from MIDI note number 0 at 8.175799 Hz. So for the Eikosany, middle C on the keyboard gets tuned two octaves low.
2. If you give it both a `.kbm` file and a `.scl` file, it still remaps the keyboard up from 8.175799 Hz. It's either ignoring the `.kbm` file or not correctly doing the mapping from the middle note specified in the `.kbm` file.

I do have a work-around. I did an export of the scale and discovered that the `.kbm` file had been changed from what I gave it. The exported `.scl` file has all 128 notes specified as cents above 8.175799 Hz, with an "octave" of 128. So I can compute the mapping I want and supply a `.scl` file for it. But that's an ugly hack and it depends on undocumented behavior in the Sound Librarian.

I did report this to Korg but I haven't heard back from them.

The files I imported are from Scala - in the attached archive, `Eikosany.scl` and `Eikosany.kbm` are the Scala output I imported to the Sound Librarian and `Eikosany-exported.*` are the files I got by exporting the map.

[Sound Librarian.zip](https://github.com/xenharmonic-devs/scale-workshop/files/10560630/Sound.Librarian.zip)

**Comment by SeanArchibald** [comment]
I see differences in the output between SW1 and SW2 (fix-korg-limit branch on local)

https://sevish.com/scaleworkshop1/?name=Subharmonics%2012-24&data=24%2F23%0A24%2F22%0A24%2F21%0A24%2F20%0A24%2F19%0A24%2F18%0A24%2F17%0A24%2F16%0A24%2F15%0A24%2F14%0A24%2F13%0A24%2F12&freq=256&midi=60&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=semisine&ampenv=organ
http://localhost:3000/scaleworkshop/?n=Subharmonics%2012-24&l=oFn_oFm_oFl_oFk_oFj_oFi_oFh_oFg_oFf_oFe_oFd_oFc&c=~-~-~&f=74&m=1o&p=1&a=5&y=334&s=0&r=rs&version=2.0.1

[Subharmonics 12-24 SW.zip](https://github.com/xenharmonic-devs/scale-workshop/files/11069350/Subharmonics.12-24.SW.zip)

SW1
SW2

**Review by SeanArchibald — APPROVED** [review]

**Pull request merged**
