### PR TITLE
Add a panic button

### PR DESCRIPTION
**Pull request by frostburn**
ref #195

### CODE REVIEW

**Comment by SeanArchibald** [comment]
Not sure if this is expected behaviour but the panic button seems to cycle through 3 states. The button displays:

Quiet - can play notes as normal
Quiet! - any held notes get stopped. But you can start playing new notes straight away
Resume - can't play any notes

**Comment by frostburn** [comment]
> Not sure if this is expected behaviour but the panic button seems to cycle through 3 states.
This is intended. The first press of the panic button cuts all notes, the second press cuts all sound and the third press returns everything back to normal.
Do you like it? We could make a hard panic button elsewhere if soft panic is enough for the main UI.

**Comment by frostburn** [comment]
Stateless panic is enough, but hard panic can be left in the codebase in case it's needed one day.

**Comment by frostburn** [comment]
Made panic stateless. Also added a missing MIDI to synth deactivation.

**Review by SeanArchibald — APPROVED** [review]

**Pull request merged**
